-- No-op.
-- This migration was generated before the tables below existed.
-- The actual ALTER TABLE statements were moved to
-- 20260803120000_add_transporters_and_receivers so migrations can be applied in order.
